#!/usr/bin/env bash
# Drives the three "before" tools end-to-end against Moto.
#
# 1. TF        -> VPC
# 2. Terragrunt -> Subnet inside that VPC
# 3. CDKTF     -> EC2 instance + SG in that subnet
#
# Pre-reqs:
# - Moto running (make local-up).
# - dev.local.env sourced OR this script will source it from repo root.
# - tofu, terragrunt, npx, node available in PATH.
#
# Each tool keeps its own local state. Resource IDs are passed between them
# via environment variables exported into a writable file ("./ids.env") so
# the import side can read them later without re-running the source tools.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
IDS_FILE="${SCRIPT_DIR}/ids.env"

# Source Moto env if the caller hasn't already.
if [[ -z "${AWS_ENDPOINT_URL_EC2:-}" ]]; then
  # shellcheck disable=SC1091
  source "${REPO_ROOT}/dev.local.env"
fi

echo "== [1/3] TF: creating VPC =="
pushd "${SCRIPT_DIR}/tf" > /dev/null
tofu init -input=false -no-color > /dev/null
tofu apply -auto-approve -input=false -no-color > /dev/null
DEMO_VPC_ID="$(tofu output -raw vpc_id)"
popd > /dev/null
echo "   VPC ID: ${DEMO_VPC_ID}"

echo "== [2/3] Terragrunt: creating subnet =="
pushd "${SCRIPT_DIR}/tg" > /dev/null
DEMO_VPC_ID="${DEMO_VPC_ID}" terragrunt run --all --non-interactive apply > /dev/null 2>&1 || \
  DEMO_VPC_ID="${DEMO_VPC_ID}" terragrunt apply -auto-approve --terragrunt-non-interactive > /dev/null
DEMO_SUBNET_ID="$(DEMO_VPC_ID="${DEMO_VPC_ID}" terragrunt output -raw subnet_id 2>/dev/null)"
popd > /dev/null
echo "   Subnet ID: ${DEMO_SUBNET_ID}"

echo "== [3/3] CDKTF: creating EC2 instance =="
# Moto returns synthetic AMIs; pick any one it knows about, otherwise use a
# placeholder Amazon Linux 2 image. Moto accepts anything that looks like
# ami-<8 or 17 hex>.
DEMO_AMI_ID="$(aws ec2 describe-images --owners amazon --query 'Images[0].ImageId' --output text 2>/dev/null || true)"
if [[ -z "${DEMO_AMI_ID}" || "${DEMO_AMI_ID}" == "None" ]]; then
  DEMO_AMI_ID="ami-12345678"
fi
echo "   Using AMI: ${DEMO_AMI_ID}"

pushd "${SCRIPT_DIR}/cdktf" > /dev/null
echo "   Installing CDKTF deps (idempotent; rerun-safe)..."
npm install --no-audit --no-fund > /dev/null
TERRAFORM_BINARY_NAME=tofu \
DEMO_VPC_ID="${DEMO_VPC_ID}" \
DEMO_SUBNET_ID="${DEMO_SUBNET_ID}" \
DEMO_AMI_ID="${DEMO_AMI_ID}" \
  npx cdktf deploy --auto-approve --no-color
DEMO_INSTANCE_ID="$(python3 -c 'import json,sys; d=json.load(open("cdktf.out/stacks/import-demo/terraform.tfstate")); print(d["outputs"]["import-demo_instance_id"]["value"])')"
DEMO_SG_ID="$(python3 -c 'import json,sys; d=json.load(open("cdktf.out/stacks/import-demo/terraform.tfstate")); print(d["outputs"]["import-demo_security_group_id"]["value"])')"
popd > /dev/null
echo "   Instance ID: ${DEMO_INSTANCE_ID}"
echo "   SG ID:       ${DEMO_SG_ID}"

cat > "${IDS_FILE}" <<EOF
# Generated by apply-sources.sh -- IDs of resources created in Moto.
# Exported in both shell-convenience (DEMO_*) and OpenTofu (TF_VAR_*) forms.
export DEMO_VPC_ID=${DEMO_VPC_ID}
export DEMO_SUBNET_ID=${DEMO_SUBNET_ID}
export DEMO_AMI_ID=${DEMO_AMI_ID}
export DEMO_INSTANCE_ID=${DEMO_INSTANCE_ID}
export DEMO_SG_ID=${DEMO_SG_ID}

export TF_VAR_vpc_id=${DEMO_VPC_ID}
export TF_VAR_subnet_id=${DEMO_SUBNET_ID}
export TF_VAR_ami_id=${DEMO_AMI_ID}
export TF_VAR_instance_id=${DEMO_INSTANCE_ID}
export TF_VAR_security_group_id=${DEMO_SG_ID}
EOF

echo ""
echo "All three tools applied. IDs written to ${IDS_FILE}."
echo "Next: cd ../target && source ../source/ids.env && tofu init && tofu plan"
